packages:
    - npm/*
    - packages/*
    - packages/__internals/*
    - packages/core/__fixtures__/app
    - packages/integrations/*
    - packages/loaders/*
    - packages/plugins/*
    - packages/processors/*
    - playground/*
    - e2e/fixtures/*
    - apps/*

allowBuilds:
    bun: true
    esbuild: true
    sharp: true
