import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.tsx'],
  darkMode: 'selector',
  theme: {
    extend: {
      colors: {
        silver: {
          50: 'var(--color-silver-50-hsla))',
          100: 'var(--color-silver-100-hsla))',
          200: 'var(--color-silver-200-hsla))',
          300: 'var(--color-silver-300-hsla))',
          400: 'var(--color-silver-400-hsla))',
          DEFAULT: 'var(--color-silver-500-hsla))',
          500: 'var(--color-silver-500-hsla))',
          600: 'var(--color-silver-600-hsla))',
          700: 'var(--color-silver-700-hsla))',
          800: 'var(--color-silver-800-hsla))',
          900: 'var(--color-silver-900-hsla))',
          950: 'var(--color-silver-950-hsla))',
        },
        'tropical-rain-forest': {
          50: 'var(--color-tropical-rain-forest-50-hsla))',
          100: 'var(--color-tropical-rain-forest-100-hsla))',
          200: 'var(--color-tropical-rain-forest-200-hsla))',
          300: 'var(--color-tropical-rain-forest-300-hsla))',
          400: 'var(--color-tropical-rain-forest-400-hsla))',
          DEFAULT: 'var(--color-tropical-rain-forest-500-hsla))',
          500: 'var(--color-tropical-rain-forest-500-hsla))',
          600: 'var(--color-tropical-rain-forest-600-hsla))',
          700: 'var(--color-tropical-rain-forest-700-hsla))',
          800: 'var(--color-tropical-rain-forest-800-hsla))',
          900: 'var(--color-tropical-rain-forest-900-hsla))',
        },
        scarlet: {
          50: 'var(--color-scarlet-50-hsla))',
          100: 'var(--color-scarlet-100-hsla))',
          200: 'var(--color-scarlet-200-hsla))',
          300: 'var(--color-scarlet-300-hsla))',
          400: 'var(--color-scarlet-400-hsla))',
          500: 'var(--color-scarlet-500-hsla))',
          DEFAULT: 'var(--color-scarlet-500-hsla))',
          600: 'var(--color-scarlet-600-hsla))',
          700: 'var(--color-scarlet-700-hsla))',
          800: 'var(--color-scarlet-800-hsla))',
          900: 'var(--color-scarlet-900-hsla))',
        },
        background: 'hsl(var(--background))',
        'on-background': 'hsl(var(--on-background))',
        'background-accent': 'hsl(var(--background-accent))',
        'on-background-accent': 'hsl(var(--on-background-accent))',
        'primary-container': 'hsl(var(--primary-container))',
        'on-primary-container': 'hsl(var(--on-primary-container))',
        primary: 'hsl(var(--primary))',
        'on-primary': 'hsl(var(--on-primary))',
        secondary: 'hsl(var(--secondary))',
        'on-secondary': 'hsl(var(--on-secondary))',
      },
    },
  },
  plugins: [],
  safelist: ['hidden'],
};

export default config;
