import { relative, resolve, dirname, join } from 'node:path';
import type { ContentEntry } from './types.ts';

function serializeEntry(entry: ContentEntry): string {
	return JSON.stringify(entry);
}

function parseEntryTypeImport(entryType: string): { module: string; name: string } {
	const [module, name = 'Entry'] = entryType.split('#');
	if (!module) {
		throw new Error(`Invalid entryType "${entryType}". Expected format: "./path/to/file#TypeName"`);
	}
	return { module, name };
}

export function renderCollectionEntriesModule(collectionName: string, manifest: ContentEntry[]): string {
	const entriesBySlugLines: string[] = [];

	for (const [index, entry] of manifest.entries()) {
		entriesBySlugLines.push(`\t'${entry.slug}': entries[${index}],`);
	}

	return `// This file is auto-generated by @ecopages/content-processor. Do not edit.

export const entries = [
${manifest.map((entry) => `\t${serializeEntry(entry)},`).join('\n')}
] as const;

const entriesBySlug: Record<string, (typeof entries)[number]> = {
${entriesBySlugLines.join('\n')}
};

export function getEntry(slug: string) {
	const entry = entriesBySlug[slug];
	if (!entry) throw new Error(\`Unknown content entry: \${slug}\`);
	return entry;
}

export function getEntryBySegments(segments: string[]) {
	return getEntry(segments.join('/'));
}
`;
}

function renderAttachMdxExportsHelper(): string {
	return `type ContentMdxModule = {
	default: EcoComponent<Record<string, unknown>>;
	config?: EcoComponent<Record<string, unknown>>['config'];
	getMetadata?: EcoComponent<Record<string, unknown>>['metadata'];
};

function attachMdxExports(module: ContentMdxModule, sourceFile: string): EcoComponent<Record<string, unknown>> {
	const Page = module.default;
	const component = Object.assign(
		(props: Record<string, unknown>) => Page(props),
		Page,
	) as EcoComponent<Record<string, unknown>>;

	if (module.config) {
		const moduleIdentity = getComponentIdentity(module.config);
		const componentIdentity = getComponentIdentity(component);
		component.config = bindComponentIdentity({
			id: moduleIdentity?.id ?? componentIdentity?.id ?? sourceFile,
			file: sourceFile,
			integration: moduleIdentity?.integration ?? componentIdentity?.integration ?? 'content',
		}, {
			...component.config,
			...module.config,
		});
	}

	if (module.getMetadata) {
		component.metadata = module.getMetadata;
	}

	return component;
}
`;
}

export function renderCollectionComponentsModule(
	_collectionName: string,
	outputDir: string,
	entrySources: Array<{ entry: ContentEntry; filePath: string }>,
): string {
	const loaderLines: string[] = [];
	const entrySourceFilesBySlugLines: string[] = [];

	for (const { entry, filePath } of entrySources) {
		const importPath = relative(outputDir, filePath).split('\\').join('/');
		const escapedImportPath = importPath.replace(/'/g, "\\'");
		const sourceFile = filePath.split('\\').join('/');
		const escapedSourceFile = sourceFile.replace(/'/g, "\\'");
		loaderLines.push(`\t'${entry.slug}': () => import('${escapedImportPath}'),`);
		entrySourceFilesBySlugLines.push(`\t'${entry.slug}': '${escapedSourceFile}',`);
	}

	return `// This file is auto-generated by @ecopages/content-processor. Do not edit.

import { bindComponentIdentity, getComponentIdentity, type EcoComponent, type PageDependenciesResult } from '@ecopages/core';

${renderAttachMdxExportsHelper()}

const loadersBySlug: Record<string, () => Promise<ContentMdxModule>> = {
${loaderLines.join('\n')}
};

const entrySourceFilesBySlug: Record<string, string> = {
${entrySourceFilesBySlugLines.join('\n')}
};

const componentCache = new Map<string, EcoComponent<Record<string, unknown>>>();
const componentLoadPromises = new Map<string, Promise<EcoComponent<Record<string, unknown>>>>();

export async function getComponent(slug: string): Promise<EcoComponent<Record<string, unknown>>> {
	const cached = componentCache.get(slug);
	if (cached) {
		return cached;
	}

	const pending = componentLoadPromises.get(slug);
	if (pending) {
		return pending;
	}

	const load = loadersBySlug[slug];
	if (!load) {
		throw new Error(\`Unknown content entry: \${slug}\`);
	}

	const loadPromise = (async () => {
		const module = await load();
		const component = attachMdxExports(module, entrySourceFilesBySlug[slug]!);
		componentCache.set(slug, component);
		return component;
	})().finally(() => {
		componentLoadPromises.delete(slug);
	});

	componentLoadPromises.set(slug, loadPromise);
	return loadPromise;
}

export async function getEntryDependencies(slug: string): Promise<PageDependenciesResult | undefined> {
	const component = await getComponent(slug);
	const dependencies = component.config?.dependencies;
	if (!dependencies) {
		return undefined;
	}

	return {
		...dependencies,
		ownerFile: entrySourceFilesBySlug[slug],
	};
}
`;
}

function resolveEntryTypeImport(
	entryType: string,
	rootDir: string,
	typesOutputFile: string,
): { module: string; name: string } {
	const { module, name } = parseEntryTypeImport(entryType);
	const absoluteModule = resolve(rootDir, module);
	const srcDir = join(rootDir, 'src');
	const relativeToSrc = relative(srcDir, absoluteModule).split('\\').join('/');

	if (!relativeToSrc.startsWith('..') && !relativeToSrc.startsWith('/')) {
		return { module: `@/${relativeToSrc}`, name };
	}

	let relativeModule = relative(dirname(typesOutputFile), absoluteModule).split('\\').join('/');
	if (!relativeModule.startsWith('.')) {
		relativeModule = `./${relativeModule}`;
	}
	return { module: relativeModule, name };
}

function renderCollectionEntriesTypesModule(
	collectionName: string,
	entryType?: string,
	typeResolution?: { rootDir: string; typesOutputFile: string },
): string {
	const entryDeclaration = entryType
		? (() => {
				const { module, name } = typeResolution
					? resolveEntryTypeImport(entryType, typeResolution.rootDir, typeResolution.typesOutputFile)
					: parseEntryTypeImport(entryType);
				return `import type { ContentEntry } from '@ecopages/content-processor/types';\n\timport type { ${name} } from '${module}';\n\texport type Entry = ContentEntry<${name}>;`;
			})()
		: `import type { ContentEntry } from '@ecopages/content-processor/types';\n\n\texport type Entry = ContentEntry<Record<string, unknown>>;`;

	return `declare module "ecopages:content/${collectionName}" {
	${entryDeclaration}

	export const entries: readonly Entry[];
	export function getEntry(slug: string): Entry;
	export function getEntryBySegments(segments: string[]): Entry;
}`;
}

function renderCollectionComponentsTypesModule(collectionName: string): string {
	return `declare module "ecopages:content/${collectionName}/server" {
	import type { EcoComponent, PageDependenciesResult } from '@ecopages/core';

	export function getComponent(slug: string): Promise<EcoComponent<Record<string, unknown>>>;
	export function getEntryDependencies(slug: string): Promise<PageDependenciesResult | undefined>;
}`;
}

export function renderCollectionTypesModule(
	collectionName: string,
	entryType?: string,
	typeResolution?: { rootDir: string; typesOutputFile: string },
): string {
	return `${renderCollectionEntriesTypesModule(collectionName, entryType, typeResolution)}\n\n${renderCollectionComponentsTypesModule(collectionName)}`;
}

export function renderVirtualModuleTypes(
	collections: Record<string, { entryType?: string }>,
	typeResolution?: { rootDir: string; typesOutputFile: string },
): string {
	return `/**
 * Do not edit manually. This file is auto-generated.
 * Virtual module types for ecopages:content/* imports.
 */

${Object.entries(collections)
	.map(([name, definition]) => renderCollectionTypesModule(name, definition.entryType, typeResolution))
	.join('\n\n')}
`;
}
