import { readFile, writeFile } from 'node:fs/promises';
import { formatCategoryTitle } from '../../content/wiki';
import { isEnoent } from './is-enoent';

export const CATALOG_GENERATED_COMMENT =
	'<!-- Generated by wiki ingest. Edit page summary frontmatter, not this file. -->';

export type CatalogPage = {
	category: string;
	slug: string;
	title: string;
	summary: string;
};

export type CatalogRenderInput = {
	categories: string[];
	pagesByTitle: Record<string, string[]>;
	entries: CatalogPage[];
};

function pageName(slug: string): string {
	const slash = slug.lastIndexOf('/');
	return slash === -1 ? slug : slug.slice(slash + 1);
}

function orderByTitles(pages: CatalogPage[], explicitTitles: string[]): CatalogPage[] {
	const remaining = new Map(pages.map((page) => [page.title, page]));
	const ordered: CatalogPage[] = [];
	for (const title of explicitTitles) {
		const page = remaining.get(title);
		if (!page) {
			continue;
		}
		ordered.push(page);
		remaining.delete(title);
	}
	ordered.push(...[...remaining.values()].sort((a, b) => a.title.localeCompare(b.title)));
	return ordered;
}

/**
 * @remarks
 * Body matches the SCHEMA catalog format. Category headings use
 * {@link formatCategoryTitle}; pages follow sidebar title order.
 */
export function renderCatalogMarkdown(input: CatalogRenderInput): string {
	const lines = [
		CATALOG_GENERATED_COMMENT,
		'',
		'# Index',
		'',
		'Catalog of wiki pages, grouped by category. Updated on every ingest.',
		'',
	];

	for (const category of input.categories) {
		const categoryPages = input.entries.filter((entry) => entry.category === category);
		if (categoryPages.length === 0) {
			continue;
		}

		const ordered = orderByTitles(categoryPages, input.pagesByTitle[category] ?? []);
		lines.push(`## ${formatCategoryTitle(category)}`, '');
		for (const page of ordered) {
			lines.push(`- [${pageName(page.slug)}](./wiki/${page.slug}.md) — ${page.summary}`);
		}
		lines.push('');
	}

	return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * @remarks
 * Skips the write when the existing file already matches, so ingest does not
 * churn mtime on an unchanged catalog.
 */
export async function writeCatalogIndex(indexPath: string, markdown: string): Promise<boolean> {
	let existing = '';
	try {
		existing = await readFile(indexPath, 'utf8');
	} catch (error) {
		if (!isEnoent(error)) {
			throw error;
		}
	}

	if (existing === markdown) {
		return false;
	}

	await writeFile(indexPath, markdown, 'utf8');
	return true;
}
