/**
 * ImageAttributes
 * These are the core attributes for the image element generated by the image processor
 */
export interface ImageAttributes {
  src: string;
  width: number;
  height: number;
  sizes: string;
  srcset?: string;
}

/**
 * This represents a single image variant created using the size configuration
 */
export interface ImageVariant {
  width: number;
  height: number;
  src: string;
  label: string;
}

/**
 * These are the core attributes for the image element and the image variants
 * This is the representation of the image element in the virtual module
 */
export interface ImageSpecifications {
  attributes: ImageAttributes;
  variants: ImageVariant[];
  /**
   * A unique key used to cache the image specifications.
   * This key should uniquely identify the combination of attributes and variants
   * to ensure proper caching behavior.
   */
  cacheKey: string;
}

/**
 * This is the representation of an image breakpoint
 * This is used to generate the srcset attribute
 */
export type ImageSize = {
  width: number;
  label: string;
};
